name: gme_options_mart
version: '1.0.0'
config-version: 2

profile: gme_options_mart

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  use_fixture: true
  risk_free_rate: 0.043
  provider_url: "https://finance.yahoo.com"

seeds:
  gme_options_mart:
    +schema: raw
