"""Mart Dashboard — Streamlit Presentation Layer

Generated by mart-forge scaffold. Reads configuration from the signed
implementation contract (mart.yml). Only contracted metrics are displayed;
link_status badges are sourced from the BRD-verified contract.
"""

import json
import os
from pathlib import Path

import duckdb
import streamlit as st
import yaml

CONTRACT_PATH = Path(__file__).parent.parent / "mart.yml"
DQC_SCORECARD_PATH = os.getenv("DQC_SCORECARD_PATH", "dqc_scorecard.json")

LINK_STATUS_LABELS = {
    "exact": ("green", "Exact verification source"),
    "proxy": ("orange", "Advisory comparator (proxy) — not ingestion provenance"),
    "unsupported": ("red", "No external comparator — see DQC scorecard"),
}


def load_contract():
    env_path = os.getenv("MART_CONTRACT_PATH")
    path = Path(env_path) if env_path else CONTRACT_PATH
    if path.exists():
        with open(path) as f:
            return yaml.safe_load(f)
    return None


@st.cache_resource
def get_connection(db_path: str):
    return duckdb.connect(db_path, read_only=True)


def load_scorecard() -> dict | None:
    p = Path(DQC_SCORECARD_PATH)
    if p.exists():
        return json.loads(p.read_text())
    return None


def load_ads_data(contract: dict):
    ads_table = contract.get("dashboard", {}).get("ads_table")
    if not ads_table:
        return None
    db_name = contract.get("mart", {}).get("db_name", "mart")
    db_path = os.getenv("MART_DB_PATH", f"{db_name}.duckdb")
    try:
        conn = get_connection(db_path)
        df = conn.execute(
            f"SELECT * FROM {ads_table} ORDER BY calendar_date"
        ).fetchdf()
        return df
    except Exception:
        return None


def render_link_badge(link_status: str) -> None:
    color, label = LINK_STATUS_LABELS.get(
        link_status, ("gray", f"Status: {link_status}")
    )
    st.caption(f":{color}_circle: {label}")


def section_mode_banner(contract: dict):
    is_fixture = os.getenv("MART_FIXTURE_MODE", "true").lower() == "true"
    if is_fixture:
        st.warning("FIXTURE/DEMO MODE — Static seed data, not live ingestion.")
    mart_name = contract.get("mart", {}).get("name", "Mart")
    st.title(f"{mart_name} Dashboard")
    db_name = contract.get("mart", {}).get("db_name", "mart")
    db_path = os.getenv("MART_DB_PATH", f"{db_name}.duckdb")
    st.caption(f"Database: {db_path}")


def section_dqc_scorecard():
    st.header("Data Quality Scorecard")
    scorecard = load_scorecard()
    if not scorecard:
        st.warning("Scorecard not found. Run `dbt test` then `dqc-update`.")
        return
    controls = scorecard.get("controls", [])
    if not controls:
        st.info("No DQC controls recorded. Run the DQC pipeline.")
        return
    cols = st.columns(min(len(controls), 4))
    for i, ctrl in enumerate(controls):
        status = ctrl.get("status", "unknown")
        color = {"pass": "green", "fail": "red", "exhausted": "orange"}.get(
            status, "gray"
        )
        with cols[i % len(cols)]:
            st.markdown(f":{color}_circle: **{ctrl.get('class', '?')}**")
            st.caption(f"{ctrl.get('metric', '?')}: {status}")
            if status == "exhausted" and "attempts" in ctrl:
                with st.expander("Resource exhaustion evidence"):
                    for a in ctrl["attempts"]:
                        st.text(
                            f"  {a.get('source','?')}: {a.get('result','?')}"
                            f" — {a.get('reason','?')}"
                        )


def section_metric_cards(contract: dict, ads_df):
    st.header("Metrics Overview")
    metrics = contract.get("metrics", [])
    if not metrics:
        st.warning("No metrics defined in implementation contract.")
        return

    if ads_df is not None and not ads_df.empty:
        display_cols = st.columns(len(metrics))
        for i, metric in enumerate(metrics):
            with display_cols[i]:
                ads_col = metric.get("ads_column", "")
                metric_id = metric.get("id", "?")
                metric_name = metric.get("name", "?")
                link_status = metric.get("link_status", "unknown")
                if ads_col and ads_col in ads_df.columns:
                    value = ads_df[ads_col].sum()
                    if float(value) == int(value):
                        formatted = f"{int(value):,}"
                    else:
                        formatted = f"{value:,.2f}"
                    st.metric(
                        label=f"{metric_name} ({metric_id})",
                        value=formatted,
                    )
                else:
                    st.metric(
                        label=f"{metric_name} ({metric_id})", value="—"
                    )
                render_link_badge(link_status)
    else:
        st.error(
            "Data unavailable — pipeline has not been run "
            "or database connection failed."
        )
        st.info("Run `dbt seed && dbt run` to populate the ADS table.")


def section_trend_chart(contract: dict, ads_df):
    st.header("Revenue Trend")
    if ads_df is not None and not ads_df.empty and "calendar_date" in ads_df.columns:
        revenue_col = None
        for metric in contract.get("metrics", []):
            if metric.get("source_type") == "native" and metric.get("ads_column"):
                revenue_col = metric["ads_column"]
                break
        if revenue_col and revenue_col in ads_df.columns:
            st.line_chart(ads_df.set_index("calendar_date")[revenue_col])
        else:
            st.info("No revenue metric found in contract.")
    else:
        st.info("No trend data available. Run `dbt seed && dbt run` first.")


def section_provenance():
    st.header("Data Provenance")
    st.markdown(
        "| Field | Description |\n"
        "|-------|------------|\n"
        "| `provider` | Data source identifier |\n"
        "| `pull_ts_utc` | When ingestion ran |\n"
        "| `quote_ts_utc` | Source data timestamp |\n"
        "| `run_id` | Pipeline run trace |"
    )


def main():
    contract = load_contract()
    mart_name = contract.get("mart", {}).get("name", "Mart") if contract else "Mart"
    st.set_page_config(page_title=f"{mart_name} Dashboard", layout="wide")
    if not contract:
        st.error(
            "Implementation contract (mart.yml) not found. "
            "Run mart-forge scaffold first."
        )
        return
    section_mode_banner(contract)
    section_dqc_scorecard()
    ads_df = load_ads_data(contract)
    section_metric_cards(contract, ads_df)
    section_trend_chart(contract, ads_df)
    section_provenance()


if __name__ == "__main__":
    main()
